const i18n = {
    es: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Temporizador",
        nav_counter: "Contadores",
        nav_checklist: "Checklist",
        nav_notes: "Notas",
        nav_calculator: "Calculadora",
        nav_reminders: "Recordatorios",
        nav_settings: "Configuración",
        pomodoro_title: "Pomodoro",
        label_work: "Trabajo \n (min)",
        label_break: "Descanso \n (min)",
        label_cycles: "Ciclos",
        btn_start: "Iniciar",
        btn_stop: "Detener",
        btn_reset: "Reset",
        pomodoro_sessions_label: "Sesiones completadas:",
        timer_title: "Temporizador",
        timer_set_time: "Toca el tiempo para ajustar",
        timer_btn_ready: "LISTO",
        placeholder_counter: "Nombre del contador",
        placeholder_checklist: "Nueva tarea",
        placeholder_notes: "Escribe tu nota aquí...",
        placeholder_reminder: "¿Qué quieres recordar?",
        placeholder_time: "Hora",
        btn_add: "Añadir",
        btn_save: "Guardar",
        btn_add_rem: "Añadir",
        btn_clear_calc: "BORRAR TODO",
        reminders_title: "Recordatorios",
        settings_title: "Configuración",
        settings_general: "General",
        settings_sounds: "Sonidos de Alarma",
        label_lang: "Idioma de la aplicación",
        label_start_mod: "Módulo al iniciar la App",
        label_sound_pomo: "Alarma Pomodoro",
        label_sound_timer: "Alarma Temporizador",
        label_sound_rem: "Alarma Recordatorios",
        sound_classic: "Clásico",
        freq_once: "Una vez",
        freq_5min: "Cada 5 min",
        freq_daily: "Diariamente",
        modal_note_title: "Editar Nota",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "¡Tiempo de trabajo terminado! A descansar.",
        pomo_notif_work: "¡Descanso terminado! Volvemos al trabajo.",
        pomo_notif_finished: "¡Felicidades! Has completado todos los ciclos.",
        timer_notif_title: "Temporizador",
        timer_notif_ended: "¡El tiempo ha terminado!",
        reminder_notif_title: "Recordatorio",
        reminder_error: "Completa texto y hora",
        counter_confirm_delete: "¿Eliminar este contador?",
        checklist_error: "Escribe una tarea primero",
        notes_confirm_delete: "¿Eliminar esta nota?",
        notes_error_empty: "Escribe algo en la nota primero",
        settings_data: "Gestión de Datos",
        btn_export: "Exportar Copia",
        btn_import: "Importar Copia",
        settings_support: "Soporte y Sugerencias",
        btn_contact: "Enviar Correo",
        settings_premium: "Versión Premium",
        premium_desc: "Elimina anuncios y apoya el desarrollo con un pago único.",
        btn_buy_premium: "OBTENER PREMIUM",
        user_premium: "¡Ya eres usuario Premium!",
        confirm_import: "Esto reemplazará tus datos actuales. ¿Continuar?",
        label_theme: "Tema de la aplicación",
        theme_light: "Claro",
        theme_dark: "Oscuro",
        label_vibration: "Vibración de botones",
        btn_delete_all: "BORRAR TODO",
        confirm_delete_all: "¡CUIDADO! Se borrarán todos tus datos permanentemente. ¿Estás seguro?",
        settings_version: "Versión",
        settings_privacy: "Política de Privacidad",
		confirm_import: "Esto borrará tus datos actuales. ¿Continuar?",
		confirm_delete_all: "¡CUIDADO! Se borrarán todos tus datos permanentemente. ¿Estás seguro?",
		error_file_size: "El archivo supera los 3MB",
		success_save: "Configuración guardada",
	// --- Configuraciones ---
        settings_premium_btn: "OBTENER VERSIÓN PREMIUM",
        settings_restore_btn: "Validar suscripción anterior",
        settings_privacy: "Política de Privacidad",
        settings_version: "Versión",
        
        // --- Mensajes de Compra ---
        confirm_premium: "¿Deseas adquirir la versión Premium para eliminar la publicidad permanentemente a través de Google Play?",
        already_premium: "¡Ya eres un usuario Premium! Gracias por tu apoyo.",
        purchase_success: "¡Compra realizada con éxito! La publicidad ha sido eliminada.",
        restoring_msg: "Consultando con Google Play Store...",
        restore_ok: "Suscripción validada. ¡Bienvenido de nuevo!",
        restore_none: "No se encontraron compras previas para esta cuenta.",
        status_premium: "✓ Cuenta Premium Activada",

        // --- Política de Privacidad Profesional ---
        privacy_text: "Daily Tools versión 1.0.0. Tu privacidad es nuestra prioridad absoluta.\n\n1. DATOS LOCALES: Todas tus notas, tareas y configuraciones se almacenan exclusivamente en la memoria interna de tu dispositivo. No tenemos acceso a tu información personal ni la enviamos a servidores externos.\n\n2. PUBLICIDAD (Google AdMob): Para mantener la aplicación gratuita, utilizamos el servicio AdMob de Google. Este servicio puede recopilar identificadores de publicidad únicos para mostrar anuncios personalizados. Puedes desactivar esto adquiriendo la versión Premium.\n\n3. PAGOS (Google Play Store): Los pagos se gestionan directamente a través de Google Play Billing Service. Daily Tools NO recopila ni almacena datos bancarios.\n\n4. PERMISOS: La aplicación requiere permisos de vibración y notificaciones para las alarmas.\n\nAl usar esta aplicación, aceptas estos términos."
		
		},
    en: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Timer",
        nav_counter: "Counters",
        nav_checklist: "Checklist",
        nav_notes: "Notes",
        nav_calculator: "Calculator",
        nav_reminders: "Reminders",
        nav_settings: "Settings",
        pomodoro_title: "Pomodoro",
        label_work: "Work \n (min)",
        label_break: "Break \n (min)",
        label_cycles: "Cycles",
        btn_start: "Start",
        btn_stop: "Stop",
        btn_reset: "Reset",
        pomodoro_sessions_label: "Completed sessions:",
        timer_title: "Timer",
        timer_set_time: "Tap time to adjust",
        timer_btn_ready: "DONE",
        placeholder_counter: "Counter name",
        placeholder_checklist: "New task",
        placeholder_notes: "Write your note here...",
        placeholder_reminder: "What do you want to remember?",
        placeholder_time: "Time",
        btn_add: "Add",
        btn_save: "Save",
        btn_add_rem: "Add",
        btn_clear_calc: "CLEAR ALL",
        reminders_title: "Reminders",
        settings_title: "Settings",
        settings_general: "General",
        settings_sounds: "Alarm Sounds",
        label_lang: "App Language",
        label_start_mod: "Start Module",
        label_sound_pomo: "Pomodoro Alarm",
        label_sound_timer: "Timer Alarm",
        label_sound_rem: "Reminders Alarm",
        sound_classic: "Classic",
        freq_once: "Once",
        freq_5min: "Every 5 min",
        freq_daily: "Daily",
        modal_note_title: "Edit Note",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "Work time over! Time to rest.",
        pomo_notif_work: "Break over! Back to work.",
        pomo_notif_finished: "Congratulations! You completed all cycles.",
        timer_notif_title: "Timer",
        timer_notif_ended: "Time's up!",
        reminder_notif_title: "Reminder",
        reminder_error: "Fill text and time",
        counter_confirm_delete: "Delete this counter?",
        checklist_error: "Write a task first",
        notes_confirm_delete: "Delete this note?",
        notes_error_empty: "Write something in the note first",
        settings_data: "Data Management",
        btn_export: "Export Backup",
        btn_import: "Import Backup",
        settings_support: "Support & Suggestions",
        btn_contact: "Send Email",
        settings_premium: "Premium Version",
        premium_desc: "Remove ads and support development with a one-time payment.",
        btn_buy_premium: "GET PREMIUM",
        user_premium: "You are a Premium user!",
        confirm_import: "This will replace your current data. Continue?",
        label_theme: "App Theme",
        theme_light: "Light",
        theme_dark: "Dark",
        label_vibration: "Button Vibration",
        btn_delete_all: "DELETE ALL",
        confirm_delete_all: "WARNING! All your data will be permanently deleted. Are you sure?",
        settings_version: "Version",
        settings_privacy: "Privacy Policy",
		confirm_import: "This will erase your current data. Continue?",
		confirm_delete_all: "WARNING! All your data will be permanently deleted. Are you sure?",
		error_file_size: "The file exceeds the 3MB limit",
		success_save: "Settings saved",
		// --- Settings ---
        settings_premium_btn: "GET PREMIUM VERSION",
        settings_restore_btn: "Restore previous purchase",
        settings_privacy: "Privacy Policy",
        settings_version: "Version",

        // --- Purchase Messages ---
        confirm_premium: "Would you like to purchase the Premium version to permanently remove ads through Google Play?",
        already_premium: "You are already a Premium user! Thank you for your support.",
        purchase_success: "Purchase successful! Ads have been removed.",
        restoring_msg: "Checking with Google Play Store...",
        restore_ok: "Subscription validated. Welcome back!",
        restore_none: "No previous purchases found for this account.",
        status_premium: "✓ Premium Account Activated",

        // --- Professional Privacy Policy ---
        privacy_text: "Daily Tools version 1.0.0. Your privacy is our absolute priority.\n\n1. LOCAL DATA: All your notes, tasks, and settings are stored exclusively in your device's internal memory. We do not have access to your personal information nor do we send it to external servers.\n\n2. ADVERTISING (Google AdMob): To keep the app free, we use Google's AdMob service. This service may collect unique advertising identifiers to show personalized ads. You can disable this by purchasing the Premium version.\n\n3. PAYMENTS (Google Play Store): Payments are managed directly through Google Play Billing Service. Daily Tools does NOT collect or store banking data.\n\n4. PERMISSIONS: The app requires vibration and notification permissions for alarms to work correctly.\n\nBy using this app, you agree to these terms."
    },
    it: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Timer",
        nav_counter: "Contatori",
        nav_checklist: "Checklist",
        nav_notes: "Note",
        nav_calculator: "Calcolatrice",
        nav_reminders: "Promemoria",
        nav_settings: "Impostazioni",
        pomodoro_title: "Pomodoro",
        label_work: "Lavoro \n (min)",
        label_break: "Pausa \n (min)",
        label_cycles: "Cicli",
        btn_start: "Inizia",
        btn_stop: "Ferma",
        btn_reset: "Reset",
        pomodoro_sessions_label: "Sessioni completate:",
        timer_title: "Timer",
        timer_set_time: "Tocca il tempo per regolare",
        timer_btn_ready: "FATTO",
        placeholder_counter: "Nome del contatore",
        placeholder_checklist: "Nuovo compito",
        placeholder_notes: "Scrivi la tua nota qui...",
        placeholder_reminder: "Cosa vuoi ricordare?",
        placeholder_time: "Ora",
        btn_add: "Aggiungi",
        btn_save: "Salva",
        btn_add_rem: "Aggiungi",
        btn_clear_calc: "CANCELLA TUTTO",
        reminders_title: "Promemoria",
        settings_title: "Impostazioni",
        settings_general: "Generale",
        settings_sounds: "Suoni Sveglia",
        label_lang: "Lingua App",
        label_start_mod: "Modulo di Avvio",
        label_sound_pomo: "Sveglia Pomodoro",
        label_sound_timer: "Sveglia Timer",
        label_sound_rem: "Sveglia Promemoria",
        sound_classic: "Classico",
        freq_once: "Una volta",
        freq_5min: "Ogni 5 min",
        freq_daily: "Quotidiano",
        modal_note_title: "Modifica Nota",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "Tempo di lavoro terminato! È ora di riposare.",
        pomo_notif_work: "Pausa finita! Si torna al lavoro.",
        pomo_notif_finished: "Congratulazioni! Hai completato tutti i cicli.",
        timer_notif_title: "Timer",
        timer_notif_ended: "Tempo scaduto!",
        reminder_notif_title: "Promemoria",
        reminder_error: "Inserisci testo e ora",
        counter_confirm_delete: "Eliminare questo contatore?",
        checklist_error: "Scrivi prima un compito",
        notes_confirm_delete: "Eliminare questa nota?",
        notes_error_empty: "Scrivi prima qualcosa nella nota",
        settings_data: "Gestione Dati",
        btn_export: "Esporta Copia",
        btn_import: "Importa Copia",
        settings_support: "Supporto e Suggerimenti",
        btn_contact: "Invia Email",
        settings_premium: "Versione Premium",
        premium_desc: "Rimuovi gli annunci e supporta lo sviluppo con un pagamento unico.",
        btn_buy_premium: "OTTIENI PREMIUM",
        user_premium: "Sei un utente Premium!",
        confirm_import: "Questo sostituirà i tuoi dati attuali. Continuare?",
        label_theme: "Tema dell'app",
        theme_light: "Chiaro",
        theme_dark: "Scuro",
        label_vibration: "Vibrazione pulsanti",
        btn_delete_all: "CANCELLA TUTTO",
        confirm_delete_all: "ATTENZIONE! Tutti i dati saranno cancellati in modo permanente. Sei sicuro?",
        settings_version: "Versione",
        settings_privacy: "Informativa sulla Privacy",
		confirm_import: "Questo cancellerà i tuoi dati attuali. Continuare?",
		confirm_delete_all: "ATTENZIONE! Tutti i tuoi dati saranno cancellati permanentemente. Sei sicuro?",
		error_file_size: "Il file supera i 3MB",
		success_save: "Impostazioni salvate",
		privacy_text: "Daily Tools 1.0.0\n\nLa tua privacy è la nostra priorità. Questa app è progettata per funzionare interamente in locale. Non raccogliamo, memorizziamo o condividiamo i tuoi dati personali, attività o note su server esterni. Tutto rimane memorizzato sul tuo dispositivo."
    },
    fr: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Minuteur",
        nav_counter: "Compteurs",
        nav_checklist: "Checklist",
        nav_notes: "Notes",
        nav_calculator: "Calculatrice",
        nav_reminders: "Rappels",
        nav_settings: "Paramètres",
        pomodoro_title: "Pomodoro",
        label_work: "Travail \n (min)",
        label_break: "Pause \n (min)",
        label_cycles: "Cycles",
        btn_start: "Démarrer",
        btn_stop: "Arrêter",
        btn_reset: "Réinitialiser",
        pomodoro_sessions_label: "Sessions terminées:",
        timer_title: "Minuteur",
        timer_set_time: "Appuyez pour ajuster",
        timer_btn_ready: "PRÊT",
        placeholder_counter: "Nom du compteur",
        placeholder_checklist: "Nouvelle tâche",
        placeholder_notes: "Écrivez votre note ici...",
        placeholder_reminder: "De quoi voulez-vous vous souvenir ?",
        placeholder_time: "Heure",
        btn_add: "Ajouter",
        btn_save: "Enregistrer",
        btn_add_rem: "Ajouter",
        btn_clear_calc: "TOUT EFFACER",
        reminders_title: "Rappels",
        settings_title: "Paramètres",
        settings_general: "Général",
        settings_sounds: "Sons d'alarme",
        label_lang: "Langue de l'application",
        label_start_mod: "Module de démarrage",
        label_sound_pomo: "Alarme Pomodoro",
        label_sound_timer: "Alarme Minuteur",
        label_sound_rem: "Alarme Rappels",
        sound_classic: "Classique",
        freq_once: "Une fois",
        freq_5min: "Toutes les 5 min",
        freq_daily: "Quotidien",
        modal_note_title: "Modifier la note",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "Temps de travail terminé ! C'est l'heure de se reposer.",
        pomo_notif_work: "Pause terminée ! Retour au travail.",
        pomo_notif_finished: "Félicitations ! Vous avez terminé tous les cycles.",
        timer_notif_title: "Minuteur",
        timer_notif_ended: "Temps écoulé !",
        reminder_notif_title: "Rappel",
        reminder_error: "Remplissez le texte et l'heure",
        counter_confirm_delete: "Supprimer ce compteur ?",
        checklist_error: "Écrivez d'abord une tâche",
        notes_confirm_delete: "Supprimer cette note ?",
        notes_error_empty: "Écrivez d'abord quelque chose dans la note",
        settings_data: "Gestion des Données",
        btn_export: "Exporter Copie",
        btn_import: "Importer Copie",
        settings_support: "Support et Suggestions",
        btn_contact: "Envoyer Email",
        settings_premium: "Version Premium",
        premium_desc: "Supprimez les publicités et soutenez le développement avec un paiement unique.",
        btn_buy_premium: "DEVENIR PREMIUM",
        user_premium: "Vous êtes déjà un utilisateur Premium !",
        confirm_import: "Cela remplacera vos données actuelles. Continuer ?",
        label_theme: "Thème de l'application",
        theme_light: "Clair",
        theme_dark: "Sombre",
        label_vibration: "Vibration des boutons",
        btn_delete_all: "TOUT EFFACER",
        confirm_delete_all: "ATTENTION ! Toutes vos données seront définitivement supprimées. Êtes-vous sûr ?",
        settings_version: "Version",
        settings_privacy: "Politique de Confidentialité",
		confirm_import: "Cela effacera vos données actuelles. Continuer ?",
		confirm_delete_all: "ATTENTION ! Toutes vos données seront définitivement supprimées. Êtes-vous sûr ?",
		error_file_size: "Le fichier dépasse 3 Mo",
		success_save: "Paramètres enregistrés",
		privacy_text: "Daily Tools 1.0.0\n\nVotre vie privée est notre priorité. Cette application est conçue pour fonctionner entièrement localement. Nous ne collectons, ne stockons ni ne partageons vos données personnelles, tâches ou notes sur des serveurs externes. Tout reste sur votre appareil."
    },
    de: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Timer",
        nav_counter: "Zähler",
        nav_checklist: "Checkliste",
        nav_notes: "Notizen",
        nav_calculator: "Rechner",
        nav_reminders: "Erinnerungen",
        nav_settings: "Einstellungen",
        pomodoro_title: "Pomodoro",
        label_work: "Arbeit \n (min)",
        label_break: "Pause \n (min)",
        label_cycles: "Zyklen",
        btn_start: "Starten",
        btn_stop: "Stoppen",
        btn_reset: "Zurücksetzen",
        pomodoro_sessions_label: "Abgeschlossene Sitzungen:",
        timer_title: "Timer",
        timer_set_time: "Zeit zum Anpassen berühren",
        timer_btn_ready: "FERTIG",
        placeholder_counter: "Name des Zählers",
        placeholder_checklist: "Neue Aufgabe",
        placeholder_notes: "Schreiben Sie Ihre Notiz hier...",
        placeholder_reminder: "Woran möchten Sie erinnert werden?",
        placeholder_time: "Zeit",
        btn_add: "Hinzufügen",
        btn_save: "Speichern",
        btn_add_rem: "Hinzufügen",
        btn_clear_calc: "ALLES LÖSCHEN",
        reminders_title: "Erinnerungen",
        settings_title: "Einstellungen",
        settings_general: "Allgemein",
        settings_sounds: "Alarmtöne",
        label_lang: "App-Sprache",
        label_start_mod: "Startmodul",
        label_sound_pomo: "Pomodoro-Alarm",
        label_sound_timer: "Timer-Alarm",
        label_sound_rem: "Erinnerungs-Alarm",
        sound_classic: "Klassisch",
        freq_once: "Einmalig",
        freq_5min: "Alle 5 Min",
        freq_daily: "Täglich",
        modal_note_title: "Notiz bearbeiten",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "Arbeitszeit vorbei! Zeit zum Ausruhen.",
        pomo_notif_work: "Pause beendet! Zurück an die Arbeit.",
        pomo_notif_finished: "Herzlichen Glückwunsch! Sie haben alle Zyklen abgeschlossen.",
        timer_notif_title: "Timer",
        timer_notif_ended: "Zeit abgelaufen!",
        reminder_notif_title: "Erinnerung",
        reminder_error: "Text und Zeit ausfüllen",
        counter_confirm_delete: "Diesen Zähler löschen?",
        checklist_error: "Schreiben Sie zuerst eine Aufgabe",
        notes_confirm_delete: "Diese Notiz löschen?",
        notes_error_empty: "Schreiben Sie zuerst etwas in die Notiz",
        settings_data: "Datenverwaltung",
        btn_export: "Backup exportieren",
        btn_import: "Backup importieren",
        settings_support: "Support & Vorschläge",
        btn_contact: "E-Mail senden",
        settings_premium: "Premium-Version",
        premium_desc: "Werbung entfernen und Entwicklung mit einer Einmalzahlung unterstützen.",
        btn_buy_premium: "PREMIUM HOLEN",
        user_premium: "Sie sind ein Premium-Benutzer!",
        confirm_import: "Dies ersetzt Ihre aktuellen Daten. Fortfahren?",
        label_theme: "App-Design",
        theme_light: "Hell",
        theme_dark: "Dunkel",
        label_vibration: "Tastenvibration",
        btn_delete_all: "ALLES LÖSCHEN",
        confirm_delete_all: "WARNUNG! Alle Ihre Daten werden dauerhaft gelöscht. Sind Sie sicher?",
        settings_version: "Version",
        settings_privacy: "Datenschutzerklärung",
		confirm_import: "Dies wird Ihre aktuellen Daten löschen. Fortfahren?",
		confirm_delete_all: "WARNUNG! Alle Ihre Daten werden dauerhaft gelöscht. Sind Sie sicher?",
		error_file_size: "Die Datei überschreitet 3 MB",
		success_save: "Einstellungen gespeichert",
		privacy_text: "Daily Tools 1.0.0\n\nIhre Privatsphäre ist unsere Priorität. Diese App ist so konzipiert, dass sie vollständig lokal funktioniert. Wir sammeln, speichern oder teilen Ihre persönlichen Daten, Aufgaben oder Notizen nicht auf externen Servern."
    },
    pt: {
        nav_pomodoro: "Pomodoro",
        nav_timer: "Temporizador",
        nav_counter: "Contadores",
        nav_checklist: "Checklist",
        nav_notes: "Notas",
        nav_calculator: "Calculadora",
        nav_reminders: "Lembretes",
        nav_settings: "Configurações",
        pomodoro_title: "Pomodoro",
        label_work: "Trabalho \n (min)",
        label_break: "Descanso \n (min)",
        label_cycles: "Ciclos",
        btn_start: "Iniciar",
        btn_stop: "Parar",
        btn_reset: "Reset",
        pomodoro_sessions_label: "Sessões concluídas:",
        timer_title: "Temporizador",
        timer_set_time: "Toque no tempo para ajustar",
        timer_btn_ready: "PRONTO",
        placeholder_counter: "Nome do contador",
        placeholder_checklist: "Nova tarefa",
        placeholder_notes: "Escreva sua nota aqui...",
        placeholder_reminder: "O que você quer lembrar?",
        placeholder_time: "Hora",
        btn_add: "Adicionar",
        btn_save: "Salvar",
        btn_add_rem: "Adicionar",
        btn_clear_calc: "LIMPAR TUDO",
        reminders_title: "Lembretes",
        settings_title: "Configurações",
        settings_general: "Geral",
        settings_sounds: "Sons de Alarme",
        label_lang: "Idioma do App",
        label_start_mod: "Módulo Inicial",
        label_sound_pomo: "Alarme Pomodoro",
        label_sound_timer: "Alarme Temporizador",
        label_sound_rem: "Alarme Lembretes",
        sound_classic: "Clássico",
        freq_once: "Uma vez",
        freq_5min: "Cada 5 min",
        freq_daily: "Diariamente",
        modal_note_title: "Editar Nota",
        pomo_notif_title: "Pomodoro",
        pomo_notif_break: "Tempo de trabalho terminado! Hora de descansar.",
        pomo_notif_work: "Intervalo terminado! De volta ao trabalho.",
        pomo_notif_finished: "Parabéns! Você completou todos os ciclos.",
        timer_notif_title: "Temporizador",
        timer_notif_ended: "O tempo acabou!",
        reminder_notif_title: "Lembrete",
        reminder_error: "Preencha o texto e a hora",
        counter_confirm_delete: "Excluir este contador?",
        checklist_error: "Escreva uma tarefa primeiro",
        notes_confirm_delete: "Excluir esta nota?",
        notes_error_empty: "Escreva algo na nota primeiro",
        settings_data: "Gestão de Dados",
        btn_export: "Exportar Cópia",
        btn_import: "Importar Cópia",
        settings_support: "Suporte e Sugestões",
        btn_contact: "Enviar E-mail",
        settings_premium: "Versão Premium",
        premium_desc: "Remova anúncios e apoie o desenvolvimento com um pagamento único.",
        btn_buy_premium: "OBTER PREMIUM",
        user_premium: "Você já é um usuário Premium!",
        confirm_import: "Isso substituirá seus dados atuais. Continuar?",
        label_theme: "Tema do aplicativo",
        theme_light: "Claro",
        theme_dark: "Escuro",
        label_vibration: "Vibração dos botões",
        btn_delete_all: "LIMPAR TUDO",
        confirm_delete_all: "CUIDADO! Todos os seus dados serão excluídos permanentemente. Você tem certeza?",
        settings_version: "Versão",
        settings_privacy: "Política de Privacidade",
		confirm_import: "Isso apagará seus dados atuais. Continuar?",
		confirm_delete_all: "CUIDADO! Todos os seus dados serão apagados permanentemente. Você tem certeza?",
		error_file_size: "O arquivo excede 3MB",
		success_save: "Configurações salvas",
		privacy_text: "Daily Tools 1.0.0\n\nA sua privacidade é a nossa prioridade. Este aplicativo foi projetado para funcionar totalmente localmente. Não coletamos, armazenamos ou compartilhamos seus dados pessoais, tarefas ou notas em servidores externos."
    }
};

window.i18n = i18n;